### ISSUE TITLE
TODO list before I switch projects

### ISSUE THREAD

**Issue by asinghvi17** [asinghvi17/RangeExtractor.jl#4]
## Docs
- [ ] Add images to docs
	- [x] Illustrate what ranges being contained vs shared means
	- [x] Illustrate the process of tiled iteration by an animation
	- [ ] Illustrate the tiling scheme ambition - cell area weighted histogram of sea ice over Greenland
- [ ] Improve the documentation's education on why this is good and how it works
## Tiling schemes
- [ ] Implement a spatial-tree tiling scheme, make sure it works!
	- [ ] add a materialization interface to tiling schemes so we know a scheme is materialized
- [ ] Add the capability to materialize per-thread (or maybe per-task, if we want a finite number of tasks) datasets for thread safety
	- [ ] Dispatch on Rasters/ArchGDAL to open threadsafe datasets
## Implementation
- [ ] In zonal ext, make sure datasets are `open` before they're acted on.  This probably needs some inspection of `parent(ras)`.
- [x] Promote zonal ext more, make sure things are masked and maybe skipmissing'ed before zonaling
- [ ] reasonable_tiling_scheme for arrays that either checks chunks or caches
- [ ] use channels wherever possible to switch out of using arrays.
- [ ] batch jobs in async tasks, weighted by compute load maybe.  this _should_ decrease the task load.  but how to measure it?
## Examples
- [ ] Greenland slope-aspect-temperature
